# Файли, які треба вилучити з білда
exclude:
  - "*/README.md"
  - LICENSE
  - .vscode
  - public

timezone: Europe/Kiev
encoding: utf-8

# Плагіни Jekyll
# Перед підключенням нового плагіну, слід додати гем плагіну в Gemfile !
plugins:
  - jekyll-minifier
  - webrick

# ==== Конфігурації плагінів ====

jekyll-minifier:
  remove_intertag_spaces: true

  uglifier_args:
    output:
      ascii_only: false

    compress:
      reduce_funcs: true
      reduce_vars: true

    mangle:
      eval: true

    harmony: true

webrick:
  # Заголовки відповідей сервера
  headers:
    X-Frame-Options: DENY

    # Сторінка може кешуватись не більше 4 днів
    #
    # Це задля того, щоб сторінка наступні рази швидше завантажувалася,
    # і щоб не пропустити свіжі оновлення
    Cache-Control: max-age=345600
