exclude: 
  - '*/README.md'
  - LICENSE
  - .vscode
  - public

timezone: Europe/Kiev
encoding: utf-8

plugins: [jekyll-minifier]

jekyll-minifier:
  remove_intertag_spaces: true

  uglifier_args:
    harmony: true
    compress: true
    #mangle: false