exclude: 
  - '*/README.md'
  - LICENSE
  - .vscode
  - public

timezone: Europe/Kiev
encoding: utf-8

plugins: 
  - jekyll-minifier
  - webrick


jekyll-minifier:
  remove_intertag_spaces: true

  uglifier_args:
    output:
      ascii_only: false

    compress:
      reduce_funcs: true
      reduce_vars: true

    mangle:
      eval: true
      toplevel: true
      properties: true

    harmony: true


webrick:
  headers:
    X-Frame-Options: DENY
