exclude: 
  - '*/README.md'
  - LICENSE
  - .vscode
  - public

timezone: Europe/Kiev
encoding: utf-8

plugins: 
  - jekyll-minifier
  - webrick


jekyll-minifier:
  remove_intertag_spaces: true

  uglifier_args:
    output:
      ascii_only: false

    compress: true
    mangle:
      eval: true
      keep_fnames: true

    source_map: true
    harmony: true


webrick:
  headers:
    X-Frame-Options: DENY
