name: Telegram notify

on: [pull_request, issues]

jobs:
  send:
    name: Sending
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        run: |
          TEXT="Новий пулл реквест чи ідея від <code>${{ github.actor }}</code>!"
          CHAT_ID=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TOKEN=${{ secrets.TELEGRAM_CHAT_ID }}

          response=$(curl -X POST -d \
            chat_id=$CHAT_ID -d \
            text=$TEXT -d \
            disable_web_page_preview=true -d \
            parse_mode=HTML \
            https://api.telegram.org/bot$TOKEN/sendMessage)

          echo "Ok!"
          echo "Response: $response"
            
